# Generated by Django 3.2.8 on 2021-11-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
