# Generated by Django 3.2.8 on 2021-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productgallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(height_field=1200, upload_to='homeslider', width_field=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
