# Generated by Django 3.2.8 on 2021-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='title',
            field=models.CharField(default='Defult', max_length=100),
            preserve_default=False,
        ),
    ]
