# Generated by Django 3.2.8 on 2021-11-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_homeslider_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='images',
            field=models.ImageField(height_field='1200px', upload_to='homeslider', width_field='300px'),
        ),
    ]
