# Generated by Django 3.2.8 on 2021-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211130_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/avatars/avatar2.png', upload_to='userprofile'),
        ),
    ]
